version: '3'
networks:
  assembly:
    ipam:
      driver: default
      config:
        - subnet: 192.26.0.1/16
services:
  database:      
    image: 'postgres:9.6'
    container_name: database
    ports:
      - '5432:5432'
    networks:
      - assembly      
    environment:
        DNSDOCK_ALIAS: soesg-db-master.docker
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: assemblies
  rabbitmq:
    image: 'rabbitmq:3.7-management'
    container_name: rabbitmq
    networks:
      - assembly
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - '5672:5672'
      - '15672:15672'
      - '25672:25672'
      - '4369:4369'
      - '5671:5671'
      - '61613:61613'
      - '61614:61614'
      - '1883:1883'
      - '8883:8883'
  prerender:
    image: lune/prerender
    container_name: prerender
    ports:
      - "4000:3000"
    networks:
      - assembly      